// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfocosanduehxlnnbzom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdmb2Nvc2FuZHVlaHhsbm5iem9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDE4OTMsImV4cCI6MjA2NjMxNzg5M30.O38LlN7pQR5mQB12w-thRxDmVCYeSl_xLiV_y106m8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);